---
- hosts: all
  sudo: True
  tasks:
  - yum:
     name: httpd
     state: present
    when: ansible_os_family == "RedHat"

  - apt:
     name: apache2
     state: present
    when: ansible_os_family == "Debian"

  - service:
       name: httpd
       state: started
    when: ansible_os_family == "RedHat"

  - service:
       name: apache2
       state: started
    when: ansible_os_family == "Debian"
